---
layout: cv
title: Zachery Volmer's CV
---
# Zachery Volmer
Computer Science student at BYU-Idaho (certificates in Computer Programming & Machine Learning; minor in Music) seeking a software development internship.

<div id="webaddress">
zvolmer@byui.edu | 509-964-4009 | <a href="https://www.linkedin.com/in/zac-volmer/">LinkedIn</a> | <a href="https://github.com/zvolmer">GitHub</a>
</div>


## Currently

Computer Science student at BYU-Idaho (certificates in Computer Programming & Machine Learning; minor in Music) seeking a software development internship.

### Specialized in

Strong knowledge of Python and C#.
Moderate knowledge of SQL, Pandas, HTML, and CSS.
Beginner knowledge of JavaScript, TypeScript, React Native and Unity.
Teamwork, leadership, critical thinking and problem solving.


### Research interests

React Native app group project.
Website for band.
Unity Target Shooter Game.


## Education

`September 2024 - Present`
__Brigham Young University - Idaho__

- Bachelors; Computer Science
- Current GPA: 3.6

`September 2022 - June 2024`
__Columbia Basin College__

- Associate; Arts and Sciences
- GPA: 3.67



## Awards

<!-- No awards listed -->


## Publications

<!-- Projects -->

### Projects

`Ongoing`
React Native app group project.

`Ongoing`
Website for band.

`Ongoing`
Unity Target Shooter Game.


## Occupation

`January 2020 - Present`
__(self-employed) - Musician__, Richland, WA

- Founded and managed a band - handled scheduling, booking, and logistics for rehearsals, recording sessions, and live concerts. Collaborated closely with a recording engineer to record two full-length albums and one EP.
- Mixed and mastered one album; earned professional certification in Pro Tools to improve production quality and workflow.
- Executed marketing and distribution strategies generating 50,000+ streams and ~200 CD sales.

`January 2022 - December 2025`
__Jamba - Shift Lead__, Richland, WA

- Operated register and managed customer transactions with precision and efficiency.
- Prepared smoothies and food items to uphold brand standards during peak hours.
- Provided leadership by delegating tasks and supporting team workflow.
- Maintained a clean and safe work environment through routine cleaning and equipment upkeep.

`January 2024 - December 2024`
__Temp-Co Heating - HVAC Assistant__, St. George, Utah

- Shadowed lead technicians in balancing air-conditioning units to optimize airflow and system performance.
- Accurately labeled piping, ductwork, and system components on construction sites to support installation and future maintenance.